---
- block: # Check for repositories and add missing ones accordingly 

  - name: Get yum repolist
    command: /usr/bin/yum repolist
    args:
      warn: no
    register: repolist
  
  - name: Add Epel repo
    package:
      name: epel-release
      state: present
    when: 
      - "ansible_os_family == 'RedHat'"
      - "ansible_distribution_major_version >= 6"
      - "'epel/x86_64' not in repolist.stdout"
    register: epelrepo
  
  - name: Add Docker repo
    template: 
      src: "{{ ansible_distribution }}-docker.repo.j2" 
      dest: /etc/yum.repos.d/docker.repo 
      owner: root 
      group: root
    register: dockerrepo

  become: true
  become_user: root
  tags: 
    - installation
    - repositories
