---
- name: Add Epel repo
  package:
    name: epel-release
    state: present
  when: 
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution_major_version >= 6"
  register: epelrepo

- name: Add Docker repo
  template: 
    src: "{{ ansible_distribution }}-docker-repo.j2" 
    dest: /etc/yum.repos.d/docker.repo 
    owner: root 
    group: root
  register: dockerrepo
