---
# tasks file for docker-engine
- block: # Make sure some packages from RH's repos are not installed.

  - name: 'Remove pre-installed version of Docker and some conflicting packages'
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux

  become: true
  become_user: root
  tags:
    - packages
    - pre-installation

- block: # Make sure we have the repositories we need

  - name: 'Add Epel repo (the easy way)'
    package:
      name: epel-release
      state: present
    when:
      - "ansible_distribution == 'CentOS'"
      - "ansible_distribution_major_version >= 7"
    register: epelrepo

  - name: 'Add Docker repo'
    template:
      src: "{{ ansible_distribution }}-docker-ce-repo.j2"
      dest: /etc/yum.repos.d/docker.repo
      owner: root
      group: root
    register: dockerrepo

  become: true
  become_user: root
  tags:
    - installation
    - repositories

- block: # Install required packages

  - name: 'Install docker-engine and python-pip from yum repos'
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-engine"
      - "python-pip"
    when:
      - epelrepo|succeeded
      - dockerrepo|succeeded
    register: installedfromrepo

  - name: 'Self-upgrade Pip'
    pip:
      name: pip
      state: latest

  # Specifically install docker-compose 1.9.0 to avoid errors when working
  # with the Docker module in current Ansible release.
  - name: Install docker-compose version 1.9.0 using pip
    pip:
      name: docker-compose
      state: present
      version: '1.9.0'

  become: true
  become_user: root
  tags:
    - installation
    - packages

- name: 'Set docker service state'
  service:
    name: docker
    state: "{{ dockerengine_state }}"
    enabled: "{{ dockerengine_enabled }}"
  become: true
  become_user: root
  tags:
    - services
