---
# tasks file for docker-engine

- block: # Check for repositories and add missing ones accordingly 

  - include: "{{ ansible_distribution }}-repos.yml"

  become: true
  become_user: root
  tags: 
    - installation
    - repositories

- block: # Install packages
  
  - name: Install docker-engine and python-pip from repos
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-engine"
      - "python-pip"
    when:
      - epelrepo|succeeded
      - dockerrepo|succeeded
    register: installedfromrepo

  - name: Self-upgrade Pip
    pip:
      name: pip
      state: latest

  - name: Install docker-py and docker-compose from Pip
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-py"
      - "docker-compose"

  become: true
  become_user: root
  tags:
    - installation
    - packages

- name: Start and enable Docker service
  service:
    name: docker
    state: "{{ dockerengine_state }}"
    enabled: "{{ dockerengine_enabled }}"
  
