---
# tasks file for docker-engine
- block: # Make sure some packages from RH's repos are not installed.

  - name: 'Remove pre-installed version of Docker and some conflicting packages'
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux

  become: true
  become_user: root
  tags:
    - packages
    - pre-installation

- block: # Make sure we have the repositories we need

  - name: 'Add Docker repo'
    template:
      src: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}-docker-ce-repo.j2"
      dest: /etc/yum.repos.d/docker.repo
      owner: root
      group: root
    register: dockerrepo

  become: true
  become_user: root
  tags:
    - installation
    - repositories

- block: # Install required packages

  - name: 'Install packages from yum repo'
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-ce"
      - "docker-ce-selinux"
      - "python-pip"
    when:
      - dockerrepo|succeeded

  - name: Install packages from pip
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-py

  become: true
  become_user: root
  tags:
    - installation
    - packages

- name: 'Set docker service state'
  service:
    name: docker
    state: "{{ dockerengine_state }}"
    enabled: "{{ dockerengine_enabled }}"
  become: true
  become_user: root
  tags:
    - services
