---
# tasks file for docker-engine

- block: # Make sure we have the repositories we need 

  - name: 'Add Epel repo (the easy way)'
    package:
      name: epel-release
      state: present
    when: 
      - "ansible_distribution == 'CentOS'"
      - "ansible_distribution_major_version >= 6"
    register: epelrepo

  - name: 'Add Docker repo'
    template: 
      src: "{{ ansible_distribution }}-docker-repo.j2" 
      dest: /etc/yum.repos.d/docker.repo 
      owner: root 
      group: root
    register: dockerrepo

  become: true
  become_user: root
  tags: 
    - installation
    - repositories

- block: # Install required packages
  
  - name: 'Install docker-engine and python-pip from repos'
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-engine"
      - "python-pip"
    when:
      - epelrepo|succeeded
      - dockerrepo|succeeded
    register: installedfromrepo

  - name: 'Self-upgrade Pip'
    pip:
      name: pip
      state: latest

  - name: 'Install docker-py and docker-compose from Pip'
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - "docker-py"
      - "docker-compose"

  become: true
  become_user: root
  tags:
    - installation
    - packages

- name: 'Set docker service state'
  service:
    name: docker
    state: "{{ dockerengine_state }}"
    enabled: "{{ dockerengine_enabled }}"
  become: true
  become_user: root
  tags:
    - services
